// Cleaned Translations Object for different languages
const translations = {
  en: {
    signInTitle: "Sign In",
    phonePlaceholder: "+91XXXXXXXXXX",
    sendOtp: "Send OTP",
    enterOtp: "Enter OTP",
    verifyOtp: "Verify OTP",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    aboutTitle: "About Our Project",
    aboutText: "Smart Irrigation is a modern solution for efficient water usage in agriculture. Our system monitors key environmental parameters and automates irrigation, helping farmers save time, water, and resources.",
    sensorsTitle: "Sensors & Components Used",
    esp32Title: "ESP32-WROOM-32D",
    esp32Summary: "Main controller with Wi-Fi and Bluetooth connectivity.",
    relayTitle: "Relay Module",
    relaySummary: "Controls devices like pumps with electrical isolation.",
    dht22Title: "DHT22 Sensor",
    dht22Summary: "Monitors temperature and humidity for smarter irrigation.",
    contactUs: "Contact Us",
    smartIrrigation: "Smart Irrigation",
    controlTitle: "Smart Irrigation - Control",
    waterPump: "💧 Water Pump",
    buzzer: "🔔 Buzzer",
    led: "💡 LED",
    turnOn: "Turn On",
    turnOff: "Turn Off",
    recommendedTitle: "Recommended Crops Based on Your Region",
    detectingLocation: "Detecting your location and weather...",
    cropName: "Crop Name",
    bestSeason: "Best Season",
    saveCrop: "Save Crop",
    nextSuggestion: "Next Suggestion",
    wheat: "Wheat",
    rice: "Rice",
    corn: "Corn",
    cotton: "Cotton",
    sugarcane: "Sugarcane",
    chilli: "Chilli",
    nextButton: "Next",
    home: "Home",
    about: "About Us",
    readings: "Readings",
    history: "History",
    control: "Control",
    news: "News",
    settings: "Settings",
    darkMode: "Dark Mode",
    logout: "Logout",
    latestNews: "Latest Agriculture News",
    loadingNews: "Loading latest agriculture news...",
    soilTitle: "Select Soil Type",
    selectSoil: "Select Your Soil Type",
    loamy: "Loamy",
    sandy: "Sandy",
    clay: "Clay",
    peat: "Peat",
    black: "Black",
    welcome: "Welcome to Agriculture Farm",
    heading: "Agriculture & Eco Farming",
    description: "There are many passages of lorem Ipsum, but the majority have suffered alteration in some form.",
    discover: "Discover More",
    signin: "Sign In",
    signup_title: "Sign Up",
    placeholder_name: "Full Name",
    btn_send_otp: "Send OTP",
    placeholder_otp: "Enter OTP",
    btn_verify_otp: "Verify OTP",
    already_account: "Already have an account?",
    signin_link: "Sign In",
    farmerTypeTitle: "Select Farmer Type",
    farmerTypeHeading: "Select Your Farmer Type",
    experienced: "Experienced Farmer",
    exp_desc: "Get advanced tools and customization options.",
    new: "New Farmer",
    new_desc: "Start with guided steps and crop suggestions.",
    gasSensorTitle: "MQ-2 Gas Sensor",
    gasSensorSummary: "Detects gas levels such as LPG, methane, smoke, and more to ensure safety in the field.",
    ldrTitle: "LDR Sensor",
    ldrSummary: "Detects ambient light levels to adjust watering schedules.",
    oledTitle: "OLED Display",
    oledSummary: "Displays real-time sensor data and system status.",
    pumpTitle: "Water Pump",
    pumpSummary: "Controls water flow to crops based on sensor inputs.",
    stepperTitle: "Stepper Motor",
    stepperSummary: "Used to rotate mechanisms like irrigation valves or solar panels.",
  },

  hi: {
    signInTitle: "साइन इन करें",
    phonePlaceholder: "+91XXXXXXXXXX",
    sendOtp: "ओटीपी भेजें",
    enterOtp: "ओटीपी दर्ज करें",
    verifyOtp: "ओटीपी सत्यापित करें",
    dontHaveAccount: "खाता नहीं है?",
    signUp: "साइन अप करें",
    aboutTitle: "हमारे प्रोजेक्ट के बारे में",
    aboutText: "स्मार्ट इरिगेशन कृषि में पानी के कुशल उपयोग के लिए एक आधुनिक समाधान है। हमारी प्रणाली प्रमुख पर्यावरणीय पैरामीटरों की निगरानी करती है और सिंचाई को स्वचालित करती है, जिससे किसानों को समय, पानी और संसाधनों की बचत होती है।",
    sensorsTitle: "सेंसर और घटक उपयोग किए गए",
    esp32Title: "ESP32-WROOM-32D",
    esp32Summary: "वायरलेस और ब्लूटूट कनेक्टिविटी के साथ मुख्य नियंत्रक।",
    relayTitle: "रिले मॉड्यूल",
    relaySummary: "पंप जैसे उपकरणों को विद्युत पृथक्करण के साथ नियंत्रित करता है।",
    dht22Title: "DHT22 सेंसर",
    dht22Summary: "स्मार्ट सिंचाई के लिए तापमान और आर्द्रता की निगरानी करता है।",
    contactUs: "संपर्क करें",
    smartIrrigation: "स्मार्ट सिंचाई",
    controlTitle: "स्मार्ट सिंचाई - नियंत्रण",
    waterPump: "💧 जल पंप",
    buzzer: "🔔 बजर",
    led: "💡 एलईडी",
    turnOn: "चालू करें",
    turnOff: "बंद करें",
    recommendedTitle: "आपके क्षेत्र के अनुसार अनुशंसित फसलें",
    detectingLocation: "आपका स्थान और मौसम पता लगाया जा रहा है...",
    cropName: "फसल का नाम",
    bestSeason: "सर्वोत्तम मौसम",
    saveCrop: "फसल सहेजें",
    nextSuggestion: "अगली अनुशंसा",
    wheat: "गेहूं",
    rice: "चावल",
    corn: "मक्का",
    cotton: "कपास",
    sugarcane: "गन्ना",
    chilli: "मिर्च",
    nextButton: "अगला",
    home: "होम",
    about: "हमारे बारे में",
    readings: "रीडिंग्स",
    history: "इतिहास",
    control: "नियंत्रण",
    news: "समाचार",
    settings: "सेटिंग्स",
    darkMode: "डार्क मोड",
    logout: "लॉग आउट",
    latestNews: "ताज़ा कृषि समाचार",
    loadingNews: "ताज़ा कृषि समाचार लोड हो रहे हैं...",
    soilTitle: "मिट्टी का प्रकार चुनें",
    selectSoil: "अपनी मिट्टी का प्रकार चुनें",
    loamy: "दोमट",
    sandy: "रेतीली",
    clay: "चिकनी",
    peat: "पीट",
    black: "काली",
    welcome: "कृषि फार्म में आपका स्वागत है",
    heading: "कृषि और इको फार्मिंग",
    description: "लोरम इप्सम के कई संस्करण हैं, लेकिन अधिकांश किसी न किसी रूप में बदल दिए गए हैं।",
    discover: "और जानें",
    signin: "साइन इन करें",
    signup_title: "साइन अप करें",
    placeholder_name: "पूरा नाम",
    btn_send_otp: "ओटीपी भेजें",
    placeholder_otp: "ओटीपी दर्ज करें",
    btn_verify_otp: "ओटीपी सत्यापित करें",
    already_account: "पहले से खाता है?",
    signin_link: "साइन इन",
    farmerTypeTitle: "किसान प्रकार चुनें",
    farmerTypeHeading: "अपना किसान प्रकार चुनें",
    experienced: "अनुभवी किसान",
    exp_desc: "उन्नत उपकरण और अनुकूलन विकल्प प्राप्त करें।",
    new: "नया किसान",
    new_desc: "निर्देशित चरणों और फसल सुझावों के साथ शुरू करें।",
    gasSensorTitle: "MQ-2 गैस सेंसर",
    gasSensorSummary: "फील्ड में सुरक्षा सुनिश्चित करने के लिए एलपीजी, मीथेन, धुआं आदि जैसी गैसों का पता लगाता है।",
    ldrTitle: "एलडीआर सेंसर",
    ldrSummary: "प्रकाश स्तर का पता लगाता है ताकि सिंचाई कार्यक्रम समायोजित किया जा सके।",
    oledTitle: "OLED डिस्प्ले",
    oledSummary: "वास्तविक समय के सेंसर डेटा और सिस्टम स्थिति को प्रदर्शित करता है।",
    pumpTitle: "वाटर पंप",
    pumpSummary: "सेंसर इनपुट के आधार पर फसलों तक पानी की आपूर्ति को नियंत्रित करता है।",
    stepperTitle: "स्टेपर मोटर",
    stepperSummary: "सिंचाई वाल्व या सोलर पैनल जैसे तंत्र को घुमाने के लिए उपयोग किया जाता है।",
  },

  te: {
    signInTitle: "సైన్ ఇన్ చేయండి",
    phonePlaceholder: "+91XXXXXXXXXX",
    sendOtp: "ఓటీపీ పంపండి",
    enterOtp: "ఓటీపీ నమోదు చేయండి",
    verifyOtp: "ఓటీపీని ధృవీకరించండి",
    dontHaveAccount: "ఖాతా లేదా?",
    signUp: "సైన్ అప్ చేయండి",
    aboutTitle: "మా ప్రాజెక్ట్ గురించి",
    aboutText: "స్మార్ట్ ఇరిగేషన్ అనేది వ్యవసాయంలో సమర్థవంతమైన నీటి వినియోగానికి ఆధునిక పరిష్కారం.",
    sensorsTitle: "సెన్సార్లు మరియు భాగాలు ఉపయోగించినవి",
    esp32Title: "ESP32-WROOM-32D",
    esp32Summary: "వై-ఫై మరియు బ్లూటూత్ కనెక్టివిటీతో ప్రధాన కంట్రోలర్.",
    relayTitle: "రిలే మాడ్యూల్",
    relaySummary: "పంప్ వంటి పరికరాలను విద్యుత్ ఐసొలేషన్‌తో నియంత్రిస్తుంది.",
    dht22Title: "DHT22 సెన్సార్",
    dht22Summary: "స్మార్ట్ ఇరిగేషన్ కోసం ఉష్ణోగ్రత మరియు ఆర్ధ్రతను పర్యవేక్షిస్తుంది.",
    contactUs: "సంప్రదించండి",
    smartIrrigation: "స్మార్ట్ ఇరిగేషన్",
    controlTitle: "స్మార్ట్ నీటిపారుదల - నియంత్రణ",
    waterPump: "💧 వాటర్ పంప్",
    buzzer: "🔔 బజర్",
    led: "💡 ఎల్ఇడి",
    turnOn: "ఆన్ చేయి",
    turnOff: "ఆఫ్ చేయి",
    recommendedTitle: "మీ ప్రాంతాన్ని ఆధారంగా పంటల సూచనలు",
    detectingLocation: "మీ స్థానం మరియు వాతావరణం గుర్తిస్తోంది...",
    cropName: "పంట పేరు",
    bestSeason: "ఉత్తమ కాలం",
    saveCrop: "పంటను సేవ్ చేయండి",
    nextSuggestion: "తర్వాతి సూచన",
    wheat: "గోధుమలు",
    rice: "బియ్యం",
    corn: "మొక్కజొన్న",
    cotton: "పత్తి",
    sugarcane: "చెరకు",
    chilli: "మిర్చి",
    nextButton: "తర్వాత",
    home: "హోమ్",
    about: "మా గురించి",
    readings: "రీడింగ్స్",
    history: "చరిత్ర",
    control: "నియంత్రణ",
    news: "వార్తలు",
    settings: "సెట్టింగ్స్",
    darkMode: "డార్క్ మోడ్",
    logout: "లాగ్ అవుట్",
    latestNews: "తాజా వ్యవసాయ వార్తలు",
    loadingNews: "తాజా వ్యవసాయ వార్తలు లోడ్ అవుతున్నాయి...",
    soilTitle: "మట్టి రకం ఎంచుకోండి",
    selectSoil: "మీ మట్టి రకం ఎంచుకోండి",
    loamy: "లోమీ",
    sandy: "సాండీ",
    clay: "క్లే",
    peat: "పీట్",
    black: "బ్లాక్",
    welcome: "వ్యవసాయ ఫారానికి స్వాగతం",
    heading: "వ్యవసాయం మరియు పర్యావరణ వ్యవసాయం",
    description: "లొరమ్ ఇప్సమ్ అనేక సంస్కరణలు ఉన్నాయి, కానీ చాలా మార్చబడ్డాయి.",
    discover: "ఇంకా తెలుసుకోండి",
    signin: "సైన్ ఇన్",
    signup_title: "సైన్ అప్",
    placeholder_name: "పూర్తి పేరు",
    btn_send_otp: "ఓటీపీ పంపండి",
    placeholder_otp: "ఓటీపీ నమోదు చేయండి",
    btn_verify_otp: "ఓటీపీని ధృవీకరించండి",
    already_account: "ఖాతా ఉందా?",
    signin_link: "సైన్ ఇన్",
    farmerTypeTitle: "రైతు రకం ఎంచుకోండి",
    farmerTypeHeading: "మీ రైతు రకం ఎంచుకోండి",
    experienced: "అనుభవం ఉన్న రైతు",
    exp_desc: "ఆధునిక సాధనాలు మరియు అనుకూల ఎంపికలతో సాగు చేయండి.",
    new: "కొత్త రైతు",
    new_desc: "దశల వారీగా సూచనలు మరియు పంటల సిఫార్సులతో ప్రారంభించండి.",
    gasSensorTitle: "MQ-2 గ్యాస్ సెన్సార్",
    gasSensorSummary: "క్షేత్రంలో భద్రత కోసం LPG, మీథేన్, పొగ వంటి గ్యాస్ స్థాయులను గుర్తిస్తుంది.",
    ldrTitle: "ఎల్డీఆర్ సెన్సార్",
    ldrSummary: "చుట్టూ ఉన్న కాంతి స్థాయిని గుర్తించి నీటి షెడ్యూలును సర్దుబాటు చేస్తుంది.",
    oledTitle: "OLED డిస్ప్లే",
    oledSummary: "అవస్థితి మరియు సెన్సార్ డేటాను తక్షణంగా ప్రదర్శిస్తుంది.",
    pumpTitle: "వాటర్ పంప్",
    pumpSummary: "సెన్సార్ డేటా ఆధారంగా పంటలకు నీరు పంపిస్తుంది.",
    stepperTitle: "స్టెప్పర్ మోటార్",
    stepperSummary: "ఇరిగేషన్ వాల్వ్‌లు లేదా సోలార్ ప్యానెల్‌లను తిప్పేందుకు ఉపయోగిస్తారు.",

  }
};


function applyLanguage(lang) {
const langData = translations[lang];

document.querySelectorAll("[data-key]").forEach(el => {
  const key = el.getAttribute("data-key");
  if (langData[key]) el.textContent = langData[key];
});

document.querySelectorAll("[data-placeholder]").forEach(el => {
  const key = el.getAttribute("data-placeholder");
  if (langData[key]) el.placeholder = langData[key];
});

document.title = langData.title || document.title;

const dropdown = document.getElementById("languageSwitcher");
if (dropdown) dropdown.value = lang;
}

function setLanguage(lang) {
localStorage.setItem('language', lang);
applyLanguage(lang);
}

// ✅ Add global switch function
function switchLanguage(event) {
const lang = event.target.value;
setLanguage(lang);
}

// On load
document.addEventListener("DOMContentLoaded", () => {
const savedLang = localStorage.getItem('language') || 'en';
applyLanguage(savedLang);
});

